language: python
python:
  - "3.6"
install:
  - pip install pandas
# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python psedonymizer_Test/pseudonymizer_testsuite.py
  - python statswrangler_Test/testsuite.py
